files:
  - source: /crowdin/cards/en-GB/*.json
    translation: /crowdin/cards/%locale%/%original_file_name%
  - source: /crowdin/booklet/en-GB/*.odt
    translation: /crowdin/booklet/%locale%/%original_file_name%
